# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "xo-tunnel"
client_id = "d9cadd3c9160e30443b03c7f2250cb12"
application_url = "https://screenshots-ir-americans-mongolia.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://screenshots-ir-americans-mongolia.trycloudflare.com/auth/callback",
  "https://screenshots-ir-americans-mongolia.trycloudflare.com/auth/shopify/callback",
  "https://screenshots-ir-americans-mongolia.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "urmine227.myshopify.com"
